### ISSUE TITLE
Darken Background?

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/hyper-smyck#1]
Might be a little too transparent right now. Switching to black or decreasing the transparency might help. Comment here if you have an opinion!

**Comment by noriakioji** [comment]
Hi Ian, thank you for creating the color scheme plugin. Like you mentioned, I think that the current background is a bit too transparent. I'd personally prefer just pure black (or a very little transparency)!

**Comment by IanMitchell** [comment]
Hey! If you want to remove the transparency, I think setting your backgroundColor to black in your config should override the theme here - if it doesn't let me know, that's a bug

**Comment by noriakioji** [comment]
I have set backgroudColor to black, but it doesn't work. I thought that the config values would be overwritten anyways...

**Comment by IanMitchell** [comment]
Hm, ok. I'll play around with it and see what I can do!

**Comment by IanMitchell** [comment]
Turns out it wasn't that hard! Should allow for background color customization now.
